version: '2'

services:
  nginx:
    image: ask-anything-dictionary-nginx
    build: ./nginx
    networks:
      - backend
    ports: 
      - "80:80"
    depends_on: 
      - flask

  flask:
    image: ask-anything-dictionary-app
    build: ./flask
    ports:
      - "5000:5000"
      
    networks:
      - backend
    environment: 
      - client_id=${client_id}
      - client_secret=${client_secret}
    links: 
      - mysql:dbdb
      
  mysql:
    image: mysql:8.0
    volumes: 
      - "./init/:/docker-entrypoint-initdb.d/"
    environment: 
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=tests
    command: mysqld
    networks:
        - backend

networks:
  backend:
    driver: bridge